name: Build Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Instalar Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: Compilar
        run: |
          qmake MutantsSurvivor.pro
          mingw32-make release

      - name: Subir el ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: MutantsSurvivor
          path: release/MutantsSurvivor.exe